//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSharpTemplate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RestSharpTemplate")]
        public string REPORT_NAME {
            get {
                return ((string)(this["REPORT_NAME"]));
            }
            set {
                this["REPORT_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso")]
        public string URL {
            get {
                return ((string)(this["URL"]));
            }
            set {
                this["URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJhbGciOiJSUzI1NiIsImtpZCI6IjZCN0FDQzUyMDMwNUJGREI0RjcyNTJEQUVCMjE3N0NDMDkxRkFBR" +
            "TEiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJhM3JNVWdNRnY5dFBjbExhNnlGM3pBa2ZxdUUifQ.eyJuYmYiOj" +
            "E1NjY1ODYwNzYsImV4cCI6MTU2NjYxNDg3NiwiaXNzIjoiaHR0cHM6Ly9hY2NzaGUudW5pbWVkYmguY2" +
            "9tLmJyLyIsImF1ZCI6Imh0dHBzOi8vYWNjc2hlLnVuaW1lZGJoLmNvbS5ici9yZXNvdXJjZXMiLCJjbG" +
            "llbnRfaWQiOiJkMjFjZmM2ZC1hMzBlLTQwOTAtOWM5ZC1hNzI1ZmJkYzdjYzMiLCJzdWIiOiI4OTMyIi" +
            "wiYXV0aF90aW1lIjoxNTY2NTg2MDc2LCJpZHAiOiJvcGVuYW0iLCJpZCI6Ijg5MzIiLCJodHRwOi8vc2" +
            "NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiR3VpbGhlcm" +
            "1lIEJydW5vIGRlIExpbWEgSnVuaW9yIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS" +
            "8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWRtMDA2MTE0NTY4OTV0c3RAdGVzdGUuY2" +
            "9tLmJyIiwiTm9tZSI6Ikd1aWxoZXJtZSBCcnVubyBkZSBMaW1hIEp1bmlvciIsIkNQRiI6IjA0NzY1OD" +
            "E1Njc2IiwiTG9naW4iOiJBRE0wMDYxMTQ1Njg5NVRTVCIsIkxvY2FsRmlzaWNvIjoiIiwiRW1wcmVzYS" +
            "I6IiIsIkF0aXZvIjoiVHJ1ZSIsIlRpcG9BdXRlbnRpY2FjYW8iOiJPcGVuQU0iLCJQcm9maWxlOjIwMz" +
            "MiOiJwYWNpZW50ZSxwYWNpZW50ZS5saXN0YXJQYWNpZW50ZSxwYWNpZW50ZS5saXN0YXJQYWNpZW50ZS" +
            "5hY2FvRWRpdGFyLHBhY2llbnRlLmxpc3RhclBhY2llbnRlLmFjYW9FeGNsdWlyLHBhY2llbnRlLmxpc3" +
            "RhclBhY2llbnRlLmV4aWJpckFjYW9FZGl0YXJFeGNsdWlyLHBhY2llbnRlLmxpc3RhclBhY2llbnRlLm" +
            "V4aWJpckxvY2FsQXRlbmRpbWVudG8scGFjaWVudGUubGlzdGFyUGFjaWVudGUuZXhpYmlyTWFyY2Fkb3" +
            "JlcyxwYWNpZW50ZS5saXN0YXJQYWNpZW50ZS5leGliaXJOb21lTWVkaWNvLHBhY2llbnRlLmxpc3Rhcl" +
            "BhY2llbnRlLmxpc3RhckxvY2Fpc0F0ZW5kaW1lbnRvLHBhY2llbnRlLmxpc3RhclBhY2llbnRlLmxpc3" +
            "Rhck1hcmNhZG9yZXMscGFjaWVudGUubGlzdGFyUGFjaWVudGUubGlzdGFyTWVkaWNvcyxwYWNpZW50ZS" +
            "5saXN0YXJQYWNpZW50ZS5saXN0YXJQZXJpb2RvQXRlbmRpbWVudG8scGFjaWVudGUubGlzdGFyUGFjaW" +
            "VudGUubm92b1BhY2llbnRlLHBhY2llbnRlLnNvbGljaXRhY2FvLmxpc3RhclNvbGljaXRhY2Flcy5lbn" +
            "ZpYXJFbWFpbCxwYWNpZW50ZS5zb2xpY2l0YWNhby5saXN0YXJTb2xpY2l0YWNhZXMuZXhwYW5kaXIscG" +
            "FjaWVudGUuc29saWNpdGFjYW8ubGlzdGFyU29saWNpdGFjYWVzLmltcHJpbWlyLHBhY2llbnRlLnNvbG" +
            "ljaXRhY2FvLmxpc3RhclNvbGljaXRhY2Flcy5zZWxlY2lvbmFyLHBhY2llbnRlLnNvbGljaXRhY2FvLm" +
            "xpc3RhclNvbGljaXRhY29lcyxwYWNpZW50ZS5zb2xpY2l0YWNhby5saXN0YXJTb2xpY2l0YWNvZXMucG" +
            "VzcXVpc2FyU29saWNpdGFjb2VzLHBhY2llbnRlLnNvbGljaXRhY2FvLmV4aWJpckNvbWJvUHJlc3RhZG" +
            "9yU29saWNpdGFudGUscGFjaWVudGUuc29saWNpdGFjYW8udmlzdWFsaXphcnNvbGljaXRhY2FvLHJlY2" +
            "VwY2FvLHJlY2VwY2FvLmxpc3Rhck1lZGljb3MsYWdlbmRhbWVudG8sYWdlbmRhbWVudG8uYXRlbmRlci" +
            "xhZ2VuZGFtZW50by5saXN0YXJNZWRpY29zLGFnZW5kYW1lbnRvLmNyaWFyQWdlbmRhbWVudG8sYWdlbm" +
            "RhbWVudG8ubGlzdGFyQWdlbmRhbWVudG9zLGFnZW5kYW1lbnRvLmFsdGVyYXJDb250YU1lZGljYSxhZ2" +
            "VuZGFtZW50by5jb250aW51YXJBdGVuZGltZW50byxhbGVydGEsYWxlcnRhLmV4aWJpclNpbm9BbGVydG" +
            "EsYWxlcnRhLmxpc3RhckFsZXJ0YXMsYXRlbmRpbWVudG8sYXRlbmRpbWVudG8uYXRlbmRpbWVudG9SZW" +
            "1vdG8sY29uZmlndXJhY2FvLGNvbmZpZ3VyYWNhby5tZW51LGNvbmZpZ3VyYWNhby5hZG1pbmlzdHJhZG" +
            "9yLGNvbmZpZ3VyYWNhby5nZXJlbmNpYXJVc3VhcmlvLGNvbmZpZ3VyYWNhby5tZW51LmV4aWJpck1ldV" +
            "BlcmZpbCxjb25maWd1cmFjYW8ubWVudS5leGliaXJDb25maWd1cmFjYW8sY29uZmlndXJhY2FvLm1lbn" +
            "UuZXhpYmlyQ29uZmlndXJhY2FvLmNvbmZpZ3VyYWNhb1Npc3RlbWEsY29uZmlndXJhY2FvLm1lbnUuZX" +
            "hpYmlyQ29uZmlndXJhY2FvLmdlcmVuY2lhclVzdWFyaW8sY29uZmlndXJhY2FvLm1lbnUuZXhpYmlyQW" +
            "RtaW5pc3RyYWRvcixjb25maWd1cmFjYW8ubWVudS5leGliaXJBbHRlcmFyTG9jYWxBdGVuZGltZW50by" +
            "xjb25maWd1cmFjYW8ubWVudS5leGliaXJTYWlyLGNvbmZpZ3VyYWNhby5tZW51LmV4aWJpckNvbmZpZ3" +
            "VyYWNhby5nZXJlbmNpYXJTZWNyZXRhcmlhcyxjb25maWd1cmFjYW8ubWVudS5leGliaXJDb25maWd1cm" +
            "Fjb2VzLGNvbmZpZ3VyYWNhby5tZW51LmV4aWJpckxpbmtQcmVzdGFkb3IsY29uZmlndXJhY2FvLm1lbn" +
            "UuZXhpYmlyTGlua1VuaW9mZmljZSxjb25maWd1cmFjYW8ubWVudS5leGliaXJNZXVQZXJmaWwuZXhpYm" +
            "lyRHVyYWNhb0NvbnN1bHRhLGZpbmFuY2Vpcm8sZmluYW5jZWlyby5jb250YU1lZGljYS5saXN0YXJDb2" +
            "50YXNNZWRpY2EucGVzcXVpc2FyQ29udGFNZWRpY2EsZmluYW5jZWlyby5jb250YU1lZGljYS5saXN0YX" +
            "JDb250YXNNZWRpY2EsZmluYW5jZWlyby5jb250YU1lZGljYS5lZGl0YXJDb250YU1lZGljYSxmaW5hbm" +
            "NlaXJvLmNvbnRhTWVkaWNhLmV4Y2x1aXJDb250YU1lZGljYSxmaW5hbmNlaXJvLmNvbnRhTWVkaWNhLn" +
            "Zpc3VhbGl6YXJDb250YU1lZGljYSxmaW5hbmNlaXJvLmNvbnRhTWVkaWNhLnZpc3VhbGl6YXJDb250YU" +
            "1lZGljYS5leGliaXJIaXN0b3JpY29Db250YSxmaW5hbmNlaXJvLmNvbnRhTWVkaWNhLnZpc3VhbGl6YX" +
            "JDb250YU1lZGljYS5leGliaXJJdGVuc0NvbnRhLGZpbmFuY2Vpcm8uY29udGFNZWRpY2EudmlzdWFsaX" +
            "phckNvbnZlbmlvLGZpbmFuY2Vpcm8uZGV0YWxoZXNDb250YU1lZGljYS5jb2x1bmFHcmlkLlRpcG8sZn" +
            "VuY2FvVXN1YXJpbyxmdW5jYW9Vc3VhcmlvLm1lZGljbyxub3RpY2lhLHBhY2llbnRlc0RvRGlhLHBhY2" +
            "llbnRlc0RvRGlhLmxpc3RhckVzcGVjaWFsaWRhZGVzLHBhY2llbnRlc0RvRGlhLmxpc3RhclByb2Zpc3" +
            "Npb25haXMscGFpbmVsUGFjaWVudGUscGFpbmVsUGFjaWVudGUuZXhpYmlyQWJhU29saWNpdGFjYW8scG" +
            "FpbmVsUGFjaWVudGUuZXhpYmlyQWJhUmVnaXN0cm9DbGluaWNvLHBhaW5lbFBhY2llbnRlLmV4aWJpck" +
            "FiYUNvbnRhTWVkaWNhLHBhaW5lbFBhY2llbnRlLmV4aWJpckFiYUhpc3RvcmljbyxwYWluZWxQYWNpZW" +
            "50ZS5leGliaXJBYmFQcmVzY3JpY2FvLHBhaW5lbFBhY2llbnRlLmV4aWJpckFiYU1vbml0b3JhbWVudG" +
            "8scGFpbmVsUGFjaWVudGUuZXhpYmlyQWJhQXRlc3RhZG8scGFpbmVsUGFjaWVudGUuZXhpYmlyQWJhRW" +
            "5jYW1pbmhhbWVudG8scGFpbmVsUGFjaWVudGUuaW5pY2lhckF0ZW5kaW1lbnRvLHBhaW5lbFBhY2llbn" +
            "RlLmZpbmFsaXphckF0ZW5kaW1lbnRvLHBhaW5lbFBhY2llbnRlLmxpc3Rhck1hcmNhZG9yZXMscGFpbm" +
            "VsUGFjaWVudGUuY3JpYXJNYXJjYWRvcixwYWluZWxQYWNpZW50ZS5leGliaXJBYmFQcm9udHVhcmlvLH" +
            "BhaW5lbFBhY2llbnRlLmV4Y2x1aXJNYXJjYWRvcmVzLHBhaW5lbFBhY2llbnRlLnJlbG9naW8scGFpbm" +
            "VsUGFjaWVudGUuZXhpYmlyQWJhQXRlc3RhZG8uc2VsZWNpb25hclRpcG9BZmFzdGFtZW50b1RyYWJhbG" +
            "hvLHBhaW5lbFBhY2llbnRlLmV4aWJpckFiYUF0ZXN0YWRvLnNlbGVjaW9uYXJUaXBvQXB0aWRhb0Zpc2" +
            "ljYU1lbnRhbCxwYWluZWxQYWNpZW50ZS5leGliaXJBYmFBdGVzdGFkby5zZWxlY2lvbmFyVGlwb0F0ZX" +
            "N0YWRvQWNvbXBhbmhhbWVudG8scGFpbmVsUGFjaWVudGUuZXhpYmlyQWJhQXRlc3RhZG8uc2VsZWNpb2" +
            "5hclRpcG9Db21wYXJlY2ltZW50byxwYWluZWxQYWNpZW50ZS5leGliaXJBYmFBdGVzdGFkby5zZWxlY2" +
            "lvbmFyVGlwb0xpY2VuY2FNYXRlcm5pZGFkZSxwYWluZWxQYWNpZW50ZS5leGliaXJBYmFTb2xpY2l0YW" +
            "Nhby5hY2Vzc2FySGlzdG9yaWNvU29saWNpdGFjb2VzLHBhaW5lbFBhY2llbnRlLmV4aWJpckFiYVNvbG" +
            "ljaXRhY2FvLnNvbGljaXRhcixtZW51TGF0ZXJhbCxtZW51TGF0ZXJhbC5BdGVuZGltZW50byxtZW51TG" +
            "F0ZXJhbC5QYWNpZW50ZXMsbWVudUxhdGVyYWwuRmluYW5jZWlybyxtZW51TGF0ZXJhbC5Ob3RpY2lhcy" +
            "IsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJlbWFpbCJdLCJhbXIiOlsiZXh0ZXJuYWwiXX0.Q8" +
            "hkX-AJ57T6EHnGK4L9gJ4LlP0lDF6_7OGyAyzApdY0SYnX3tSdt8vTqzM1vpst3zansSxI0sj-DklJFJ" +
            "pYPhFznDLikWZTlO24X6e1D6tc497hWUgMTaDYkvM-hBavs4I-rYa30BEaR1ahBzshMwoiGWXjrwfqQK" +
            "zlBuMbLDsT6uD7q8VCkpMAAMAYWHhCvx4TRxNGpnI4KjB-TjMCw7OiOqWfBwbZw2RRf-73cF8I05MiCd" +
            "jndE28MgT791JN1HeQL6RWj9rWd632Xcw1W4qdJpO06wIMqs8zmuN3HzJcr52mibZHbG5sJZl8FwAHKM" +
            "mm9pD2FJ9CJRbO-I1TCg\r\n")]
        public string TOKEN {
            get {
                return ((string)(this["TOKEN"]));
            }
            set {
                this["TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public int REPORT_SUBSTRING_LENGTH {
            get {
                return ((int)(this["REPORT_SUBSTRING_LENGTH"]));
            }
            set {
                this["REPORT_SUBSTRING_LENGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("solsrvtstsql.database.windows.net")]
        public string DB_URL {
            get {
                return ((string)(this["DB_URL"]));
            }
            set {
                this["DB_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cresqltst")]
        public string DB_NAME {
            get {
                return ((string)(this["DB_NAME"]));
            }
            set {
                this["DB_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("solusrbs2rd")]
        public string DB_USER {
            get {
                return ((string)(this["DB_USER"]));
            }
            set {
                this["DB_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oof6qHZgRktDl3VP04ZX")]
        public string DB_PASSWORD {
            get {
                return ((string)(this["DB_PASSWORD"]));
            }
            set {
                this["DB_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string DB_CONNECTION_TIMEOUT {
            get {
                return ((string)(this["DB_CONNECTION_TIMEOUT"]));
            }
            set {
                this["DB_CONNECTION_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usuarioAuthentication")]
        public string AUTHENTICATOR_USER {
            get {
                return ((string)(this["AUTHENTICATOR_USER"]));
            }
            set {
                this["AUTHENTICATOR_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("senhaAuthentication")]
        public string AUTHENTICATOR_PASSWORD {
            get {
                return ((string)(this["AUTHENTICATOR_PASSWORD"]));
            }
            set {
                this["AUTHENTICATOR_PASSWORD"] = value;
            }
        }
    }
}
